PosClient/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using PosShared.Models;
using System.Text.Json;
using PosShared;
using System.Text;
using PosShared.ViewModels;
using PosShared.DTOs;
using PosClient.Services;

namespace PosClient.Controllers;

public class ItemsController : Controller
{
    private readonly ApiService _apiService;

    public ItemsController(ApiService apiService)
    {
        _apiService = apiService;
    }
    
    // GET: Items/Index
    public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 20)
    {
        var apiUrl = ApiRoutes.Items.GetItemsPaginated(pageNumber,pageSize);
        var response = await _apiService.GetAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            var jsonData = await response.Content.ReadAsStringAsync();
            var items = JsonSerializer.Deserialize<PaginatedResult<Item>>(jsonData, JsonOptions.Default);
            return View(items);
        }

        TempData["Error"] = "Could not retrieve items.";
        return View(new PaginatedResult<Item>());
    }


    // GET: Items/Create
    public IActionResult Create()
    {
        return View(new ItemViewModel());
    }

    // POST: Items/Create
    [HttpPost]
    public async Task<IActionResult> Create(ItemViewModel item)
    {
        if (item == null)
        {
            ModelState.AddModelError(string.Empty, "Invalid item data.");
            return View(item);
        }

        var apiUrl = ApiRoutes.Items.CreateItem;
        var itemJson = JsonSerializer.Serialize(item);
        var content = new StringContent(itemJson, Encoding.UTF8, "application/json");

        var response = await _apiService.PostAsync(apiUrl, content);

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction(nameof(Index));
        }

        var errorMessage = await response.Content.ReadAsStringAsync();
        ModelState.AddModelError(string.Empty, $"Error creating item: {errorMessage}");

        return View(item);
    }

    // GET: Items/Edit/
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var apiUrl = ApiRoutes.Items.GetItemById(id);
        var response = await _apiService.GetAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            var itemData = await response.Content.ReadAsStringAsync();
            var item = JsonSerializer.Deserialize<Item>(itemData, JsonOptions.Default);

            if (item != null)
            {
                var itemViewModel = new ItemViewModel
                {
                    Name = item.Name,
                    Description = item.Description,
                    Price = item.Price,
                    BasePrice = item.BasePrice,
                    Category = item.Category,
                    Quantity = item.Quantity
                };

                return View(itemViewModel);
            }
        }

        TempData["Error"] = "Unable to fetch item details. Please try again.";
        return RedirectToAction("Index");
    }


    // POST: Items/Edit/
    [HttpPost]
    public async Task<IActionResult> Edit(int id, ItemViewModel item)
    {
        
        if (ModelState.IsValid)
        {
            var apiUrl = ApiRoutes.Items.UpdateItem(id);
            var content = new StringContent(JsonSerializer.Serialize(item), Encoding.UTF8, "application/json");

            var response = await _apiService.PutAsync(apiUrl, content);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            TempData["Error"] = "Failed to update item.";
        }

        return View(item);
    }

    // GET: Items/Delete/{id}
    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var apiUrl = ApiRoutes.Items.GetItemById(id);
        var response = await _apiService.GetAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            var itemData = await response.Content.ReadAsStringAsync();
            var item = JsonSerializer.Deserialize<Item>(itemData, JsonOptions.Default);

            if (item != null)
            {
                return View(item);
            }
        }
        TempData["Error"] = "Could not delete item, if its part of an order, it cannot be deleted";

        return NotFound();
    }

    // POST: Items/Delete/{id}
    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var apiUrl = ApiRoutes.Items.DeleteItem(id);
        var response = await _apiService.DeleteAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("Index");
        }

        ViewBag.ErrorMessage = "Failed to delete item.";
        return RedirectToAction("Index");
    }

    #region Variations

    // GET: Items/Variations/{itemId}
    [HttpGet]
    public async Task<IActionResult> Variations(int itemId)
    {
        ViewBag.ItemId = itemId; // Pass ItemId to the view

        var apiUrl = ApiRoutes.Items.GetItemVariations(itemId);
        var response = await _apiService.GetAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            var jsonData = await response.Content.ReadAsStringAsync();
            var variations = JsonSerializer.Deserialize<List<ItemVariation>>(jsonData,JsonOptions.Default);

            return View("Variations/Variations", variations);
        }

        ViewBag.ErrorMessage = "Could not retrieve variations for the item.";
        return View("Variations/Variations", new List<ItemVariation>());
    }

    // GET: Items/Variations/Create/{itemId}
    [HttpGet]
    public IActionResult VariationCreate(int itemId)
    {
        var model = new ItemVariationCreateViewModel
        {
            ItemId = itemId
        };

        return View("Variations/Create", model);
    }

    // POST: Items/Variations/Create
    [HttpPost]
    public async Task<IActionResult> VariationCreate(ItemVariationCreateViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View("Variations/Create", model);
        }
        
        var apiUrl = ApiRoutes.Items.CreateVariation(model.ItemId);

        var variation = new ItemVariation()
        {
            Name = model.Name,
            AdditionalPrice = model.AdditionalPrice,
            ItemId = model.ItemId,
        };

        var variationJson = JsonSerializer.Serialize(variation);
        var content = new StringContent(variationJson, Encoding.UTF8, "application/json");
        Console.WriteLine(variationJson);
        var response = await _apiService.PostAsync(apiUrl, content);

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("Variations", new { itemId = model.ItemId });
        }

        var errorMessage = await response.Content.ReadAsStringAsync();
        ModelState.AddModelError(string.Empty, $"Error creating variation: {errorMessage}");
        TempData["Error"] = errorMessage;
        return View("Variations/Create", model);
    }



    // GET: Items/Variations/Edit/
    [HttpGet]
    public async Task<IActionResult> EditVariation(int id)
    {
        var apiUrl = ApiRoutes.Items.GetItemVariationById(id);
        var response = await _apiService.GetAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            var variationData = await response.Content.ReadAsStringAsync();

            VariationsDTO? variation = JsonSerializer.Deserialize<VariationsDTO>(variationData, JsonOptions.Default);

            if (variation != null)
            {
                return View("Variations/Edit", variation);
            }
        }

        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> EditVariation(int id, VariationsDTO variation)
    {
        if (!ModelState.IsValid)
        {
            TempData["Error"] = "Invalid input.";

            return View("Variations/Edit", variation);
        }

        var apiUrl = ApiRoutes.Items.UpdateVariation(id);
        var content = new StringContent(JsonSerializer.Serialize(variation), Encoding.UTF8, "application/json");

        var response = await _apiService.PutAsync(apiUrl, content);
        if (!response.IsSuccessStatusCode)
        {
            TempData["Error"] = "Failed to update the variation.";
            return View("Variations/Edit", variation);
        }

        return RedirectToAction("Variations", new { itemId = variation.ItemId });
    }




    // POST: Items/Variations/Delete/
    [HttpPost]
    public async Task<IActionResult> DeleteVariation([FromForm] int id, [FromForm] int varId)
    {
        var apiUrl = ApiRoutes.Items.DeleteItem(id);
        var response = await _apiService.DeleteAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            return RedirectToAction("Variations", new { itemId = id });
        }

        TempData["Error"] = "Failed to delete variation.";
        return RedirectToAction("Variations", new { itemId = id });
    }
    #endregion

}

PosClient/Controllers/TaxController.cs
using Microsoft.AspNetCore.Mvc;
using PosClient.Services;
using PosShared;
using PosShared.DTOs;
using PosShared.Models;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace PosClient.Controllers
{
    public class TaxController : Controller
    {
        private readonly ApiService _apiService;

        private readonly string _apiUrl = ApiRoutes.ApiBaseUrl;

        public TaxController(ApiService apiService, IUserSessionService userSessionService)
        {
            _apiService = apiService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var response = await _apiService.GetAsync(ApiRoutes.Tax.List);
            if (response.IsSuccessStatusCode)
            {
                var taxData = await response.Content.ReadAsStringAsync();
                var taxes = JsonSerializer.Deserialize<List<Tax>>(taxData, JsonOptions.Default);
                return View(taxes);
            }

            TempData["Error"] = "Unable to fetch taxes." + response.StatusCode;
            return View(new List<Tax>());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TaxDTO tax)
        {
            var content = new StringContent(JsonSerializer.Serialize(tax), Encoding.UTF8, "application/json");
            var response = await _apiService.PostAsync(ApiRoutes.Tax.Create, content);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            TempData["Error"] = "Failed to create tax. See if tax with same category does not already exist.\n" + response.StatusCode;
            return View(tax);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var response = await _apiService.GetAsync(ApiRoutes.Tax.GetById(id));
            if (response.IsSuccessStatusCode)
            {
                var taxData = await response.Content.ReadAsStringAsync();
                var tax = JsonSerializer.Deserialize<Tax>(taxData, JsonOptions.Default);
                
                TaxDTO taxDto = new TaxDTO()
                {
                    Amount = tax.Amount,
                    Name = tax.Name,
                    IsPercentage = tax.IsPercentage,
                    Category = tax.Category
                };

                return View(taxDto);
            }

            TempData["Error"] = "Failed to fetch tax." + response.StatusCode;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, TaxDTO tax)
        {
            var content = new StringContent(JsonSerializer.Serialize(tax), Encoding.UTF8, "application/json");

            var response = await _apiService.PutAsync(ApiRoutes.Tax.Update(id), content);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            TempData["Error"] = "Failed to update tax. " + response.StatusCode;
            return View(tax);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _apiService.DeleteAsync(ApiRoutes.Tax.Delete(id));
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            TempData["Error"] = "Failed to delete tax. " + response.StatusCode;
            return RedirectToAction("Index");
        }
        
    }
}

PosClient/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using PosShared.Models;
using System.Text.Json;
using System.Text;
using PosShared;
using PosShared.ViewModels;
using PosClient.Services;
using PosShared.DTOs;

namespace PosClient.Controllers;

public class UserController : Controller
{
    private readonly ApiService _apiService;

    private readonly string _apiUrl = ApiRoutes.ApiBaseUrl;

    public UserController(ApiService apiService)
    {
        _apiService = apiService;

    }

    // GET: User/Index
    public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 10)
    {
        var apiUrl = ApiRoutes.User.ListPaginated(pageNumber, pageSize);
        var response = await _apiService.GetAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            var jsonData = await response.Content.ReadAsStringAsync();
            var users = JsonSerializer.Deserialize<PaginatedResult<User>>(jsonData, JsonOptions.Default);
            return View(users);
        }

        TempData["Error"] = "Could not retrieve users." + response.Content;
        return View(new PaginatedResult<User>());
    }

    // GET: User/Create
    public IActionResult Create()
    {
        return View(new CreateUserDTO());
    }

    // POST: User/Create
    [HttpPost]
    public async Task<IActionResult> Create(CreateUserDTO newUser)
    {
        if (ModelState.IsValid)
        {
            var apiUrl = ApiRoutes.User.Create;
            var content = new StringContent(JsonSerializer.Serialize(newUser), Encoding.UTF8, "application/json");

            var response = await _apiService.PostAsync(apiUrl, content);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            TempData["Error"] = "Failed to create user.";
        }

        return View(newUser);
    }


    // GET: User/Edit/
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var apiUrl = ApiRoutes.User.GetById(id);
        var response = await _apiService.GetAsync(apiUrl);

        if(response.IsSuccessStatusCode)
        {
            string userData = await response.Content.ReadAsStringAsync();
            UserDTO? user = JsonSerializer.Deserialize<UserDTO>(userData,JsonOptions.Default);
            
            if (user != null)
            {
                UserViewModel model = new UserViewModel()
                {
                    Id = user.Id,
                    BusinessId = user.BusinessId,
                    Username = user.Username,
                    Name = user.Name,
                    Email = user.Email,
                    Phone = user.Phone,
                    Address = user.Address,
                    Role = user.Role,
                    EmploymentStatus = user.EmploymentStatus
                };

                return View(model);
            }
        }

        return NotFound();
    }

    // POST: User/Edit/
    [HttpPost]
    public async Task<IActionResult> Edit(int id, UserViewModel user)
    {
        if (ModelState.IsValid)
        {
            var apiUrl = ApiRoutes.User.Update(id);
            
            UserDTO dto = new UserDTO();
            dto.Id = user.Id;
            dto.BusinessId = user.BusinessId;
            dto.Username = user.Username;
            dto.Name = user.Name;
            dto.Email = user.Email;
            dto.Phone = user.Email;
            dto.Address = user.Address;
            dto.Role = user.Role;
            dto.EmploymentStatus = user.EmploymentStatus;
            
            var content = new StringContent(JsonSerializer.Serialize(dto), Encoding.UTF8, "application/json");

            var response = await _apiService.PutAsync(apiUrl, content);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            TempData["Error"] = $"Failed to update user. Status code:{response.StatusCode}";
        }

        return View(user);
    }

    // GET: User/Delete/
    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var apiUrl = ApiRoutes.User.GetById(id);
        var response = await _apiService.GetAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            var userData = await response.Content.ReadAsStringAsync();
            var user = JsonSerializer.Deserialize<User>(userData,JsonOptions.Default);

            if (user != null)
            {
                return View(user);
            }
        }

        return NotFound();
    }

    // POST: User/Delete/
    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var apiUrl = ApiRoutes.User.Delete(id);
        var response = await _apiService.DeleteAsync(apiUrl);

        if (response.IsSuccessStatusCode)
        {
            TempData["Message"] = $"Deleted user {id}. Status code:{response.StatusCode}";
            return RedirectToAction("Index");
        }

        TempData["Error"] = $"Failed to delete user. Status code:{response.StatusCode}";
        return RedirectToAction("Index");
    }
    
}

PosClient/Views/Shared/_Layout.cshtml
@using PosClient.Services
@using PosShared.Models
@inject IUserSessionService UserSessionService

@{
    var userRole = UserSessionService.GetCurrentUserRole()?.ToString();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PosClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PosClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PosClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (userRole == "SuperAdmin" || userRole == "Owner" || userRole == "Manager" || userRole == "Worker")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        @if (userRole == "SuperAdmin" || userRole == "Owner")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Business" asp-action="Index">Business</a>
                            </li>
                        }
                        @if (userRole == "SuperAdmin" || userRole == "Owner" || userRole == "Manager")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        }

                        @if (userRole == "SuperAdmin" || userRole == "Owner" || userRole == "Manager" || userRole == "Worker")
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">Items</a>
                            </li>
                        

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tax" asp-action="Index">Tax</a>
                            </li>
                        
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Service" asp-action="Index">Services</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservations</a>
                            </li>
                        
                        }
                    </ul>
                    <div class="navbar-right">
                        @if (userRole != null)
                        {
                            <ul class="navbar-nav d-flex flex-row align-items-center">
                                <li>
                                    <a><span class="fw-bold">User role:</span> @userRole</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white btn btn-danger btn-sm" asp-area="" asp-controller="Home" asp-action="ChangePassword"><span class="fw-bold">Change password</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white btn btn-danger btn-sm" asp-area="" asp-controller="Home" asp-action="Logout"><span class="fw-bold">Log out</span></a>
                                </li>
                            </ul>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PosClient - <a asp-area="" asp-controller="" asp-action=""></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>